'use client';

import { MantineProvider, AppShell } from '@mantine/core';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <MantineProvider>
        <AppShell>
          <AppShell.Header
            withBorder={false}
          >
            {/* // <Header
              //   mobileOpened={mobileOpened}
              //   toggleMobile={toggleMobile}
              // /> */}
          </AppShell.Header>

          <AppShell.Navbar p="md">
            {/* <div style={{ width: '100%', display: 'flex', flexDirection: 'row-reverse' }}>
              <Burger color="#523f91" onClick={toggleMobile} opened={mobileOpened} size="md" />
            </div> */}
          </AppShell.Navbar>

          {children}
          {/* <Footer /> */}
        </AppShell>
      </MantineProvider>
    </body>
  </html>
);

export default RootLayout;
